import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        display: ['var(--font-display)', 'Newsreader', 'Georgia', 'serif'],
        serif:   ['var(--font-serif)', 'Newsreader', 'Georgia', 'serif'],
        sans:    ['var(--font-body)', 'ui-sans-serif', 'system-ui', '-apple-system', 'Helvetica Neue', 'Arial', 'sans-serif'],
        arabic:  ['var(--font-arabic)', 'Cairo', 'sans-serif'],
        mono:    ['var(--font-mono)', '"IBM Plex Mono"', 'ui-monospace', 'Menlo', 'monospace'],
      },
      spacing: {
        '4.5': '1.125rem', // 18px — standard button/inline icon size
        '5.5': '1.375rem', // 22px — section marker icon size
      },
      fontSize: {
        'display': ['80px', { lineHeight: '1', letterSpacing: '-0.03em', fontWeight: '400' }],
        'hero':    ['36px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'title':   ['20px', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'body':    ['13px', { lineHeight: '1.55', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '1.5', fontWeight: '400' }],
        'label':   ['10px', { lineHeight: '1.4', letterSpacing: '0.1em', fontWeight: '600' }],
        'micro':   ['10px', { lineHeight: '1.4', letterSpacing: '0.1em', fontWeight: '600' }],
        'metric':  ['44px', { lineHeight: '1', letterSpacing: '-0.02em', fontWeight: '400' }],
      },
      colors: {
        border: {
          DEFAULT: "hsl(var(--border))",
          subtle: 'rgba(0,0,0,0.07)',
          strong: 'rgba(0,0,0,0.2)',
          'subtle-dark':  'rgba(255,255,255,0.06)',
          'default-dark': 'rgba(255,255,255,0.1)',
        },
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
          hover: "hsl(var(--card-hover))",
        },
        gold: {
          DEFAULT: "hsl(var(--primary))",
          light: 'var(--gold-light)',
          dark:  'var(--gold-dark)',
          glow:  'var(--gold-glow)',
          pale:  'var(--gold-pale)',
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        brand: {
          DEFAULT: 'var(--action)',
          hover:   'var(--spot)',
          pale:    'var(--paper-2)',
          muted:   'var(--rule)',
        },
        ink: {
          DEFAULT: 'var(--ink)',
          2: 'var(--ink-2)',
          3: 'var(--ink-3)',
          4: 'var(--ink-4)',
          5: 'var(--ink-5)',
          /* Back-compat aliases used by older components */
          6: 'var(--ink-4)',
          7: 'var(--ink-3)',
        },
        paper: {
          DEFAULT: 'var(--paper)',
          2: 'var(--paper-2)',
          3: 'var(--paper-3)',
        },
        vellum: 'var(--vellum)',
        /* System-A scales */
        rule:     'var(--rule)',
        spot:     { DEFAULT: 'var(--spot)', 2: 'var(--spot-2)' },
        obsidian: { DEFAULT: 'var(--ob-bg)', page: 'var(--ob-page)', panel: 'var(--ob-panel)', raised: 'var(--ob-raised)', field: 'var(--ob-field)' },
        hair:     { DEFAULT: 'var(--hair)', grid: 'var(--grid)' },
        glass:    { DEFAULT: 'var(--glass)', 2: 'var(--glass-2)', 3: 'var(--glass-3)' },
        live:     'var(--live)',
        action:   'var(--action)',
        pos:      'var(--pos)',
        neg:      'var(--neg)',
        semantic: {
          success:        'var(--semantic-success)',
          'success-light':'var(--semantic-success-light)',
          danger:         'var(--semantic-danger)',
          'danger-light': 'var(--semantic-danger-light)',
          warning:        'var(--semantic-warning)',
          'warning-light':'var(--semantic-warning-light)',
          info:           'var(--semantic-info)',
          'info-light':   'var(--semantic-info-light)',
        },
        signal: {
          orange:        'var(--signal-orange)',
          'orange-light':'var(--signal-orange-light)',
        },
        surface: {
          page:        'var(--paper)',
          DEFAULT:     '#FFFFFF',
          raised:      '#FFFFFF',
          subtle:      'var(--paper-2)',
          ink:         'var(--ink)',
          'ink-raised':'var(--surface-ink-raised)',
          'ink-subtle':'var(--surface-ink-subtle)',
        },
        status: {
          'high-bg':      '#FDECEA',
          'high-text':    '#B83025',
          'medium-bg':    '#FEF3C7',
          'medium-text':  '#92400E',
          'good-bg':      '#FEF0E6',
          'good-text':    '#C05A10',
          'perfect-bg':   '#EAF4EB',
          'perfect-text': '#2E7D38',
          'trusted-bg':   '#EAF4EB',
          'trusted-text': '#2E7D38',
          'act-bg':       '#0E0D0C',
          'act-text':     '#FFFFFF',
          'emerging-bg':  '#EEF2FF',
          'emerging-text':'#3730A3',
          'capture-bg':   '#EEF2FF',
          'capture-text': '#3730A3',
          'publish-bg':   '#FEF0E6',
          'publish-text': '#C05A10',
        },
        success: { DEFAULT: 'var(--pos)', pale: 'rgba(111,191,142,0.12)', light: 'var(--pos)' },
        danger:  { DEFAULT: 'var(--neg)', pale: 'rgba(217,138,130,0.12)', light: 'var(--neg)' },
        warning: { DEFAULT: 'var(--action)', pale: 'rgba(214,167,72,0.12)', light: 'var(--action)' },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "20px",
        '2xl': "24px",
        full: "9999px",
        instrument: '16px',
        control:    '8px',
        sharp:      '2px',
      },
      boxShadow: {
        card:        '0 1px 3px rgba(0,0,0,0.06), 0 4px 16px rgba(0,0,0,0.05)',
        'card-hover':'0 2px 8px rgba(0,0,0,0.08), 0 12px 32px rgba(0,0,0,0.07)',
        brand:       '0 8px 24px -8px rgba(8,12,17,0.18)',
        'brand-sm':  '0 1px 2px rgba(8,12,17,0.06)',
        inset:       '0 30px 60px -28px rgba(8,12,17,.55)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(8px)", filter: "blur(4px)" },
          "100%": { opacity: "1", transform: "translateY(0)", filter: "blur(0)" },
        },
        "fade-out": {
          "0%": { opacity: "1", transform: "translateY(0)" },
          "100%": { opacity: "0", transform: "translateY(8px)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.97)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "slide-up": {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "tab-enter": {
          "0%": { opacity: "0", transform: "translateY(12px)", filter: "blur(3px)" },
          "100%": { opacity: "1", transform: "translateY(0)", filter: "blur(0)" },
        },
        "ticker-scroll": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "shimmer": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "fade-out": "fade-out 0.3s ease-out forwards",
        "scale-in": "scale-in 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "slide-up": "slide-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "tab-enter": "tab-enter 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "ticker-scroll": "ticker-scroll 240s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
