import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        display: ['var(--font-display)', 'Cormorant Garamond', 'Georgia', 'serif'],
        serif: ['var(--font-display)', 'Cormorant Garamond', 'Georgia', 'serif'],
        sans: ['"DM Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display': ['80px', { lineHeight: '1', letterSpacing: '-0.03em', fontWeight: '400' }],
        'hero':    ['36px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'title':   ['20px', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'body':    ['13px', { lineHeight: '1.55', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '1.5', fontWeight: '400' }],
        'label':   ['10px', { lineHeight: '1.4', letterSpacing: '0.1em', fontWeight: '600' }],
        'micro':   ['9px',  { lineHeight: '1.4', letterSpacing: '0.12em', fontWeight: '600' }],
      },
      colors: {
        border: {
          DEFAULT: "hsl(var(--border))",
          subtle: 'rgba(0,0,0,0.07)',
          strong: 'rgba(0,0,0,0.2)',
          'subtle-dark':  'rgba(255,255,255,0.06)',
          'default-dark': 'rgba(255,255,255,0.1)',
        },
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
          hover: "hsl(var(--card-hover))",
        },
        gold: {
          DEFAULT: "hsl(var(--primary))",
          glow: "hsl(var(--gold-glow))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        brand: {
          DEFAULT: '#B08D3A',
          hover:   '#8C6E26',
          pale:    '#F0E6C9',
          muted:   'rgba(176,141,58,0.22)',
        },
        ink: {
          DEFAULT: '#0E0D0C',
          2: '#1A1916',
          3: '#2A2825',
          4: '#3D3A36',
          5: '#6B6866',
          6: '#9A9690',
          7: '#B4B0AA',
        },
        surface: {
          page:        '#F8F5F0',
          DEFAULT:     '#FFFFFF',
          raised:      '#FFFFFF',
          subtle:      '#F3F0EB',
          ink:         '#0E0D0C',
          'ink-raised':'var(--surface-ink-raised)',
          'ink-subtle':'var(--surface-ink-subtle)',
        },
        status: {
          'high-bg':      '#FDECEA',
          'high-text':    '#B83025',
          'medium-bg':    '#FEF3C7',
          'medium-text':  '#92400E',
          'good-bg':      '#FEF0E6',
          'good-text':    '#C05A10',
          'perfect-bg':   '#EAF4EB',
          'perfect-text': '#2E7D38',
          'trusted-bg':   '#EAF4EB',
          'trusted-text': '#2E7D38',
          'act-bg':       '#0E0D0C',
          'act-text':     '#FFFFFF',
          'emerging-bg':  '#EEF2FF',
          'emerging-text':'#3730A3',
          'capture-bg':   '#EEF2FF',
          'capture-text': '#3730A3',
          'publish-bg':   '#FEF0E6',
          'publish-text': '#C05A10',
        },
        success: { DEFAULT: '#2E7D38', pale: '#EAF4EB', light: '#5BBF6A' },
        danger:  { DEFAULT: '#B83025', pale: '#FDECEA', light: '#E24B4A' },
        warning: { DEFAULT: '#92400E', pale: '#FEF3C7', light: '#BA7517' },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "20px",
        '2xl': "24px",
        full: "9999px",
      },
      boxShadow: {
        card:        '0 1px 3px rgba(0,0,0,0.06), 0 4px 16px rgba(0,0,0,0.05)',
        'card-hover':'0 2px 8px rgba(0,0,0,0.08), 0 12px 32px rgba(0,0,0,0.07)',
        brand:       '0 4px 20px rgba(176,141,58,0.35)',
        'brand-sm':  '0 2px 12px rgba(176,141,58,0.30)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(8px)", filter: "blur(4px)" },
          "100%": { opacity: "1", transform: "translateY(0)", filter: "blur(0)" },
        },
        "fade-out": {
          "0%": { opacity: "1", transform: "translateY(0)" },
          "100%": { opacity: "0", transform: "translateY(8px)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.97)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "slide-up": {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "tab-enter": {
          "0%": { opacity: "0", transform: "translateY(12px)", filter: "blur(3px)" },
          "100%": { opacity: "1", transform: "translateY(0)", filter: "blur(0)" },
        },
        "ticker-scroll": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "shimmer": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "fade-out": "fade-out 0.3s ease-out forwards",
        "scale-in": "scale-in 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "slide-up": "slide-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "tab-enter": "tab-enter 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "ticker-scroll": "ticker-scroll 240s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
