import LegalPage from "./LegalPage";
import usePageMeta from "@/hooks/usePageMeta";

const Terms = () => {
  usePageMeta({
    title: "Aura — Terms",
    description: "Aura terms of service: how we license the platform, what you own, acceptable use, AI-generated content disclaimers, and account termination.",
    path: "/terms",
  });
  return (
    <LegalPage
      title="Terms of Service"
      updated="May 2026"
      sections={[
        { title: "About Aura", body: "Aura is a strategic intelligence platform for senior professionals. By using Aura, you agree to these terms." },
        { title: "Your Account", body: "You are responsible for maintaining the confidentiality of your login credentials." },
        { title: "Your Content", body: "You retain ownership of all content you capture, generate, or publish through Aura. We do not claim ownership of your data." },
        { title: "Our Service", body: "We provide the service \"as is\" and will make reasonable efforts to maintain availability and security." },
        { title: "Acceptable Use", body: "You agree not to use Aura for any unlawful purpose." },
        { title: "AI-Generated Content", body: "Content generated by Aura is AI-assisted, based on your captures and signals. You should review all generated content before publishing. Aura is not responsible for the accuracy, completeness, or consequences of content you choose to publish." },
        { title: "Limitation of Liability", body: "Aura is provided on an 'as is' basis without warranties of any kind, express or implied. To the maximum extent permitted by applicable law, Aura and its creators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service." },
        { title: "Termination", body: "Either party may terminate at any time. Upon termination, your data will be retained for 30 days before permanent deletion." },
        { title: "Contact", body: "mohammad.mahafdhah@aura-intel.org" },
      ]}
    />
  );
};

export default Terms;