-- 04 — primary keys, uniques, checks, foreign keys, then indexes.
ALTER TABLE public.admin_action_log ADD CONSTRAINT admin_action_log_pkey PRIMARY KEY (id);
ALTER TABLE public.admin_settings ADD CONSTRAINT admin_settings_pkey PRIMARY KEY (key);
ALTER TABLE public.agent_findings ADD CONSTRAINT agent_findings_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_usage_log ADD CONSTRAINT ai_usage_log_pkey PRIMARY KEY (id);
ALTER TABLE public.api_health_checks ADD CONSTRAINT api_health_checks_pkey PRIMARY KEY (id);
ALTER TABLE public.assessment_sessions ADD CONSTRAINT assessment_sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.audience_demographics ADD CONSTRAINT audience_demographics_pkey PRIMARY KEY (id);
ALTER TABLE public.audience_insights ADD CONSTRAINT audience_insights_pkey PRIMARY KEY (id);
ALTER TABLE public.aura_conversation_memory ADD CONSTRAINT aura_conversation_memory_pkey PRIMARY KEY (id);
ALTER TABLE public.authority_scores ADD CONSTRAINT authority_scores_pkey PRIMARY KEY (id);
ALTER TABLE public.authority_voice_profiles ADD CONSTRAINT authority_voice_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.beta_allowlist ADD CONSTRAINT beta_allowlist_pkey PRIMARY KEY (id);
ALTER TABLE public.beta_feedback ADD CONSTRAINT beta_feedback_pkey PRIMARY KEY (id);
ALTER TABLE public.capability_dimensions ADD CONSTRAINT capability_dimensions_pkey PRIMARY KEY (id);
ALTER TABLE public.capability_radar_snapshots ADD CONSTRAINT capability_radar_snapshots_pkey PRIMARY KEY (id);
ALTER TABLE public.capability_responses ADD CONSTRAINT capability_responses_pkey PRIMARY KEY (id);
ALTER TABLE public.captures ADD CONSTRAINT captures_pkey PRIMARY KEY (id);
ALTER TABLE public.chat_conversations ADD CONSTRAINT chat_conversations_pkey PRIMARY KEY (id);
ALTER TABLE public.chat_messages ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);
ALTER TABLE public.contact_messages ADD CONSTRAINT contact_messages_pkey PRIMARY KEY (id);
ALTER TABLE public.content_gate_cache ADD CONSTRAINT content_gate_cache_pkey PRIMARY KEY (content_hash);
ALTER TABLE public.content_gate_results ADD CONSTRAINT content_gate_results_pkey PRIMARY KEY (id);
ALTER TABLE public.content_items ADD CONSTRAINT content_items_pkey PRIMARY KEY (id);
ALTER TABLE public.content_lineage ADD CONSTRAINT content_lineage_pkey PRIMARY KEY (id);
ALTER TABLE public.daily_brief_snapshots ADD CONSTRAINT daily_brief_snapshots_pkey PRIMARY KEY (id);
ALTER TABLE public.decisions ADD CONSTRAINT decisions_pkey PRIMARY KEY (id);
ALTER TABLE public.deck_events ADD CONSTRAINT deck_events_pkey PRIMARY KEY (id);
ALTER TABLE public.decks ADD CONSTRAINT decks_pkey PRIMARY KEY (id);
ALTER TABLE public.deleted_test_accounts_20260818 ADD CONSTRAINT deleted_test_accounts_20260818_pkey PRIMARY KEY (id);
ALTER TABLE public.design_system ADD CONSTRAINT design_system_pkey PRIMARY KEY (id);
ALTER TABLE public.desk_answer_feedback ADD CONSTRAINT desk_answer_feedback_pkey PRIMARY KEY (id);
ALTER TABLE public.desk_eval_questions ADD CONSTRAINT desk_eval_questions_pkey PRIMARY KEY (id);
ALTER TABLE public.desk_eval_runs ADD CONSTRAINT desk_eval_runs_pkey PRIMARY KEY (id);
ALTER TABLE public.desk_learning ADD CONSTRAINT desk_learning_pkey PRIMARY KEY (id);
ALTER TABLE public.desk_number_violations ADD CONSTRAINT desk_number_violations_pkey PRIMARY KEY (id);
ALTER TABLE public.diagnostic_profiles ADD CONSTRAINT diagnostic_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.discovery_review_queue ADD CONSTRAINT discovery_review_queue_pkey PRIMARY KEY (id);
ALTER TABLE public.document_briefs ADD CONSTRAINT document_briefs_pkey PRIMARY KEY (id);
ALTER TABLE public.document_chunks ADD CONSTRAINT document_chunks_pkey PRIMARY KEY (id);
ALTER TABLE public.document_jobs ADD CONSTRAINT document_jobs_pkey PRIMARY KEY (id);
ALTER TABLE public.documents ADD CONSTRAINT documents_pkey PRIMARY KEY (id);
ALTER TABLE public.draft_edits ADD CONSTRAINT draft_edits_pkey PRIMARY KEY (id);
ALTER TABLE public.ef_error_log ADD CONSTRAINT ef_error_log_pkey PRIMARY KEY (id);
ALTER TABLE public.ef_event_log_retired_20260724 ADD CONSTRAINT ef_event_log_pkey PRIMARY KEY (id);
ALTER TABLE public.entries ADD CONSTRAINT entries_pkey PRIMARY KEY (id);
ALTER TABLE public.eval_metrics ADD CONSTRAINT eval_metrics_pkey PRIMARY KEY (id);
ALTER TABLE public.evidence_fragments ADD CONSTRAINT evidence_fragments_pkey PRIMARY KEY (id);
ALTER TABLE public.evidence_jobs ADD CONSTRAINT evidence_jobs_pkey PRIMARY KEY (id);
ALTER TABLE public.external_costs ADD CONSTRAINT external_costs_pkey PRIMARY KEY (id);
ALTER TABLE public.facet_states ADD CONSTRAINT facet_states_pkey PRIMARY KEY (id);
ALTER TABLE public.focus_accounts ADD CONSTRAINT focus_accounts_pkey PRIMARY KEY (id);
ALTER TABLE public.framework_activations ADD CONSTRAINT framework_activations_pkey PRIMARY KEY (id);
ALTER TABLE public.freshness_checks ADD CONSTRAINT freshness_checks_pkey PRIMARY KEY (check_key);
ALTER TABLE public.funnel_daily_ratio ADD CONSTRAINT funnel_daily_ratio_pkey PRIMARY KEY (day);
ALTER TABLE public.guide_articles ADD CONSTRAINT guide_articles_pkey PRIMARY KEY (id);
ALTER TABLE public.guide_slug_misses ADD CONSTRAINT guide_slug_misses_pkey PRIMARY KEY (slug, surface);
ALTER TABLE public.health_findings ADD CONSTRAINT health_findings_pkey PRIMARY KEY (id);
ALTER TABLE public.home_address ADD CONSTRAINT home_address_pkey PRIMARY KEY (id);
ALTER TABLE public.identity_registry ADD CONSTRAINT identity_registry_pkey PRIMARY KEY (id);
ALTER TABLE public.impact_narratives ADD CONSTRAINT impact_narratives_pkey PRIMARY KEY (id);
ALTER TABLE public.import_jobs ADD CONSTRAINT import_jobs_pkey PRIMARY KEY (id);
ALTER TABLE public.imprint_snapshots ADD CONSTRAINT imprint_snapshots_pkey PRIMARY KEY (id);
ALTER TABLE public.industry_trends ADD CONSTRAINT industry_trends_pkey PRIMARY KEY (id);
ALTER TABLE public.influence_snapshots ADD CONSTRAINT influence_snapshots_pkey PRIMARY KEY (id);
ALTER TABLE public.instrument_runs ADD CONSTRAINT instrument_runs_pkey PRIMARY KEY (id);
ALTER TABLE public.job_queue ADD CONSTRAINT job_queue_pkey PRIMARY KEY (id);
ALTER TABLE public.known_issues ADD CONSTRAINT known_issues_pkey PRIMARY KEY (id);
ALTER TABLE public.learned_intelligence ADD CONSTRAINT learned_intelligence_pkey PRIMARY KEY (id);
ALTER TABLE public.lifecycle_email_log ADD CONSTRAINT lifecycle_email_log_pkey PRIMARY KEY (id);
ALTER TABLE public.lifecycle_emails ADD CONSTRAINT lifecycle_emails_pkey PRIMARY KEY (id);
ALTER TABLE public.linkedin_connections ADD CONSTRAINT linkedin_connections_pkey PRIMARY KEY (id);
ALTER TABLE public.linkedin_post_metrics ADD CONSTRAINT linkedin_post_metrics_pkey PRIMARY KEY (id);
ALTER TABLE public.linkedin_posts ADD CONSTRAINT linkedin_posts_pkey PRIMARY KEY (id);
ALTER TABLE public.linkedin_profile_snapshots ADD CONSTRAINT linkedin_profile_snapshots_pkey PRIMARY KEY (id);
ALTER TABLE public.market_mirror_cache ADD CONSTRAINT market_mirror_cache_pkey PRIMARY KEY (id);
ALTER TABLE public.master_frameworks ADD CONSTRAINT master_frameworks_pkey PRIMARY KEY (id);
ALTER TABLE public.member_issue_reports ADD CONSTRAINT member_issue_reports_pkey PRIMARY KEY (id);
ALTER TABLE public.metric_targets ADD CONSTRAINT metric_targets_pkey PRIMARY KEY (id);
ALTER TABLE public.mirror_reads ADD CONSTRAINT mirror_reads_pkey PRIMARY KEY (handle);
ALTER TABLE public.mirror_requests ADD CONSTRAINT mirror_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.narrative_suggestions ADD CONSTRAINT narrative_suggestions_pkey PRIMARY KEY (id);
ALTER TABLE public.notification_events ADD CONSTRAINT notification_events_pkey PRIMARY KEY (id);
ALTER TABLE public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.onboarding_article_log ADD CONSTRAINT onboarding_article_log_pkey PRIMARY KEY (id);
ALTER TABLE public.onboarding_questions ADD CONSTRAINT onboarding_questions_pkey PRIMARY KEY (id);
ALTER TABLE public.operation_runs ADD CONSTRAINT operation_runs_pkey PRIMARY KEY (id);
ALTER TABLE public.ops_alerts ADD CONSTRAINT ops_alerts_pkey PRIMARY KEY (id);
ALTER TABLE public.output_leak_log ADD CONSTRAINT output_leak_log_pkey PRIMARY KEY (id);
ALTER TABLE public.page_backgrounds ADD CONSTRAINT page_backgrounds_pkey PRIMARY KEY (id);
ALTER TABLE public.post_events ADD CONSTRAINT post_events_pkey PRIMARY KEY (id);
ALTER TABLE public.product_events ADD CONSTRAINT product_events_pkey PRIMARY KEY (id);
ALTER TABLE public.product_facts ADD CONSTRAINT product_facts_pkey PRIMARY KEY (id);
ALTER TABLE public.profile_copy_drafts ADD CONSTRAINT profile_copy_drafts_pkey PRIMARY KEY (id);
ALTER TABLE public.qa_audit_results ADD CONSTRAINT qa_audit_results_pkey PRIMARY KEY (id);
ALTER TABLE public.qa_reports ADD CONSTRAINT qa_reports_pkey PRIMARY KEY (id);
ALTER TABLE public.qa_runs ADD CONSTRAINT qa_runs_pkey PRIMARY KEY (id);
ALTER TABLE public.read_queue ADD CONSTRAINT read_queue_pkey PRIMARY KEY (id);
ALTER TABLE public.recommended_moves_retired_20260718 ADD CONSTRAINT recommended_moves_pkey PRIMARY KEY (id);
ALTER TABLE public.register_options ADD CONSTRAINT register_options_pkey PRIMARY KEY (id);
ALTER TABLE public.report_shares ADD CONSTRAINT report_shares_pkey PRIMARY KEY (token);
ALTER TABLE public.report_snapshots ADD CONSTRAINT report_snapshots_pkey PRIMARY KEY (id);
ALTER TABLE public.request_snapshots ADD CONSTRAINT request_snapshots_pkey PRIMARY KEY (id);
ALTER TABLE public.retrieval_logs ADD CONSTRAINT retrieval_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.score_snapshots ADD CONSTRAINT score_snapshots_pkey PRIMARY KEY (id);
ALTER TABLE public.seniority_titles ADD CONSTRAINT seniority_titles_pkey PRIMARY KEY (title);
ALTER TABLE public.ship_markers ADD CONSTRAINT ship_markers_pkey PRIMARY KEY (id);
ALTER TABLE public.signal_engagements ADD CONSTRAINT signal_engagements_pkey PRIMARY KEY (user_id, signal_id);
ALTER TABLE public.signal_topic_preferences ADD CONSTRAINT signal_topic_preferences_pkey PRIMARY KEY (id);
ALTER TABLE public.signature_events ADD CONSTRAINT signature_events_pkey PRIMARY KEY (id);
ALTER TABLE public.signup_attempts ADD CONSTRAINT signup_attempts_pkey PRIMARY KEY (id);
ALTER TABLE public.signup_ceiling_alerts ADD CONSTRAINT signup_ceiling_alerts_pkey PRIMARY KEY (ip_hash);
ALTER TABLE public.signup_refusals ADD CONSTRAINT signup_refusals_pkey PRIMARY KEY (id);
ALTER TABLE public.skill_targets ADD CONSTRAINT skill_targets_pkey PRIMARY KEY (id);
ALTER TABLE public.source_events ADD CONSTRAINT source_events_pkey PRIMARY KEY (id);
ALTER TABLE public.source_registry ADD CONSTRAINT source_registry_pkey PRIMARY KEY (id);
ALTER TABLE public.strategic_signals ADD CONSTRAINT strategic_signals_pkey PRIMARY KEY (id);
ALTER TABLE public.sync_errors ADD CONSTRAINT sync_errors_pkey PRIMARY KEY (id);
ALTER TABLE public.sync_runs ADD CONSTRAINT sync_runs_pkey PRIMARY KEY (id);
ALTER TABLE public.theme_aliases ADD CONSTRAINT theme_aliases_pkey PRIMARY KEY (id);
ALTER TABLE public.training_logs ADD CONSTRAINT training_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.user_milestones ADD CONSTRAINT user_milestones_pkey PRIMARY KEY (id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);
ALTER TABLE public.user_widget_layout ADD CONSTRAINT user_widget_layout_pkey PRIMARY KEY (user_id);
ALTER TABLE public.voice_distribution ADD CONSTRAINT voice_distribution_pkey PRIMARY KEY (id);
ALTER TABLE public.voice_feedback ADD CONSTRAINT voice_feedback_pkey PRIMARY KEY (id);
ALTER TABLE public.voice_learning_prefs ADD CONSTRAINT voice_learning_prefs_pkey PRIMARY KEY (user_id);
ALTER TABLE public.voice_post_outcomes ADD CONSTRAINT voice_post_outcomes_pkey PRIMARY KEY (id);
ALTER TABLE public.voice_rules ADD CONSTRAINT voice_rules_pkey PRIMARY KEY (id);
ALTER TABLE public.voice_trait_registry ADD CONSTRAINT voice_trait_registry_pkey PRIMARY KEY (id);
ALTER TABLE public.voice_trait_rejections ADD CONSTRAINT voice_trait_rejections_pkey PRIMARY KEY (id);
ALTER TABLE public.voice_traits ADD CONSTRAINT voice_traits_pkey PRIMARY KEY (id);
ALTER TABLE public.weekly_missions ADD CONSTRAINT weekly_missions_pkey PRIMARY KEY (id);
ALTER TABLE public.whatsapp_links ADD CONSTRAINT whatsapp_links_pkey PRIMARY KEY (id);
ALTER TABLE public.whatsapp_messages ADD CONSTRAINT whatsapp_messages_pkey PRIMARY KEY (id);
ALTER TABLE public.widget_slot_votes ADD CONSTRAINT widget_slot_votes_pkey PRIMARY KEY (id);
ALTER TABLE public.assessment_sessions ADD CONSTRAINT assessment_sessions_token_key UNIQUE (token);
ALTER TABLE public.authority_scores ADD CONSTRAINT authority_scores_user_id_snapshot_date_key UNIQUE (user_id, snapshot_date);
ALTER TABLE public.beta_allowlist ADD CONSTRAINT beta_allowlist_email_key UNIQUE (email);
ALTER TABLE public.capability_responses ADD CONSTRAINT capability_responses_user_id_dimension_id_key UNIQUE (user_id, dimension_id);
ALTER TABLE public.daily_brief_snapshots ADD CONSTRAINT daily_brief_snapshots_date_run_key UNIQUE (brief_date, run_seq);
ALTER TABLE public.desk_learning ADD CONSTRAINT desk_learning_unique UNIQUE (user_id, kind, observation);
ALTER TABLE public.diagnostic_profiles ADD CONSTRAINT diagnostic_profiles_user_id_key UNIQUE (user_id);
ALTER TABLE public.document_briefs ADD CONSTRAINT document_briefs_doc_version_unique UNIQUE (document_id, pipeline_version);
ALTER TABLE public.facet_states ADD CONSTRAINT facet_states_unique_user_facet UNIQUE (user_id, facet);
ALTER TABLE public.focus_accounts ADD CONSTRAINT focus_accounts_user_id_name_key UNIQUE (user_id, name);
ALTER TABLE public.guide_articles ADD CONSTRAINT guide_articles_slug_key UNIQUE (slug);
ALTER TABLE public.home_address ADD CONSTRAINT home_address_user_id_address_date_key UNIQUE (user_id, address_date);
ALTER TABLE public.identity_registry ADD CONSTRAINT identity_registry_user_id_key UNIQUE (user_id);
ALTER TABLE public.influence_snapshots ADD CONSTRAINT influence_snapshots_user_id_snapshot_date_source_type_key UNIQUE (user_id, snapshot_date, source_type);
ALTER TABLE public.lifecycle_email_log ADD CONSTRAINT lifecycle_email_log_user_id_message_key_key UNIQUE (user_id, message_key);
ALTER TABLE public.linkedin_post_metrics ADD CONSTRAINT linkedin_post_metrics_post_id_snapshot_date_key UNIQUE (post_id, snapshot_date);
ALTER TABLE public.linkedin_posts ADD CONSTRAINT linkedin_posts_user_id_linkedin_post_id_key UNIQUE (user_id, linkedin_post_id);
ALTER TABLE public.market_mirror_cache ADD CONSTRAINT market_mirror_cache_user_id_key UNIQUE (user_id);
ALTER TABLE public.page_backgrounds ADD CONSTRAINT page_backgrounds_page_key_theme_key UNIQUE (page_key, theme);
ALTER TABLE public.post_events ADD CONSTRAINT post_events_post_id_event_at_key UNIQUE (post_id, event, at);
ALTER TABLE public.product_facts ADD CONSTRAINT product_facts_key_key UNIQUE (key);
ALTER TABLE public.profile_copy_drafts ADD CONSTRAINT profile_copy_drafts_user_id_target_key UNIQUE (user_id, target);
ALTER TABLE public.register_options ADD CONSTRAINT register_options_label_key UNIQUE (label);
ALTER TABLE public.request_snapshots ADD CONSTRAINT request_snapshots_response_id_key UNIQUE (response_id);
ALTER TABLE public.signal_topic_preferences ADD CONSTRAINT signal_topic_preferences_user_id_theme_tag_key UNIQUE (user_id, theme_tag);
ALTER TABLE public.skill_targets ADD CONSTRAINT skill_targets_user_id_pillar_key UNIQUE (user_id, pillar);
ALTER TABLE public.source_events ADD CONSTRAINT source_events_unique_intake UNIQUE (user_id, source_table, source_id, event_type);
ALTER TABLE public.source_registry ADD CONSTRAINT source_registry_user_id_source_type_source_id_key UNIQUE (user_id, source_type, source_id);
ALTER TABLE public.theme_aliases ADD CONSTRAINT theme_aliases_alias_canonical_locale_key UNIQUE (alias, canonical, locale);
ALTER TABLE public.user_milestones ADD CONSTRAINT user_milestones_user_id_milestone_id_key UNIQUE (user_id, milestone_id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_role_key UNIQUE (user_id, role);
ALTER TABLE public.voice_distribution ADD CONSTRAINT voice_distribution_user_id_language_key UNIQUE (user_id, language);
ALTER TABLE public.voice_post_outcomes ADD CONSTRAINT voice_post_outcomes_post_id_key UNIQUE (post_id);
ALTER TABLE public.voice_trait_registry ADD CONSTRAINT voice_trait_registry_trait_key_key UNIQUE (trait_key);
ALTER TABLE public.voice_traits ADD CONSTRAINT voice_traits_profile_id_trait_key_key UNIQUE (profile_id, trait_key);
ALTER TABLE public.whatsapp_links ADD CONSTRAINT whatsapp_links_pair_token_key UNIQUE (pair_token);
ALTER TABLE public.whatsapp_links ADD CONSTRAINT whatsapp_links_phone_e164_key UNIQUE (phone_e164);
ALTER TABLE public.whatsapp_links ADD CONSTRAINT whatsapp_links_user_id_key UNIQUE (user_id);
ALTER TABLE public.whatsapp_messages ADD CONSTRAINT whatsapp_messages_wa_message_id_key UNIQUE (wa_message_id);
ALTER TABLE public.widget_slot_votes ADD CONSTRAINT widget_slot_votes_user_id_slot_key_key UNIQUE (user_id, slot_key);
ALTER TABLE public.agent_findings ADD CONSTRAINT agent_findings_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'kept'::text, 'dismissed'::text, 'below_bar'::text, 'duplicate'::text, 'error'::text, 'skipped'::text])));
ALTER TABLE public.authority_voice_profiles ADD CONSTRAINT authority_voice_profiles_mode_key_check CHECK (((mode_key IS NULL) OR (mode_key = ANY (ARRAY['executive'::text, 'thought_leadership'::text, 'educational'::text, 'personal'::text, 'contrarian'::text, 'default'::text]))));
ALTER TABLE public.authority_voice_profiles ADD CONSTRAINT authority_voice_profiles_readiness_check CHECK (((readiness IS NULL) OR (readiness = ANY (ARRAY['forming'::text, 'developing'::text, 'working'::text, 'reliable'::text, 'distinctive'::text]))));
ALTER TABLE public.beta_allowlist ADD CONSTRAINT beta_allowlist_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'active'::text, 'invited'::text])));
ALTER TABLE public.beta_feedback ADD CONSTRAINT beta_feedback_rating_check CHECK (((rating >= 1) AND (rating <= 10)));
ALTER TABLE public.capability_responses ADD CONSTRAINT capability_responses_level_check CHECK (((level >= 1) AND (level <= 3)));
ALTER TABLE public.chat_messages ADD CONSTRAINT chat_messages_role_check CHECK ((role = ANY (ARRAY['user'::text, 'assistant'::text])));
ALTER TABLE public.content_items ADD CONSTRAINT content_items_arrived_by_check CHECK ((arrived_by = ANY (ARRAY['published_through_aura'::text, 'imported_by_member'::text, 'discovered_by_search'::text, 'entered_by_member'::text, 'generated_in_place'::text, 'unknown'::text])));
ALTER TABLE public.content_items ADD CONSTRAINT content_items_confidence_check CHECK ((confidence = ANY (ARRAY['confirmed'::text, 'reported'::text, 'guessed'::text, 'unknown'::text])));
ALTER TABLE public.content_items ADD CONSTRAINT content_items_made_by_check CHECK ((made_by = ANY (ARRAY['member'::text, 'aura'::text, 'aura_edited_by_member'::text, 'machine'::text, 'unknown'::text])));
ALTER TABLE public.content_items ADD CONSTRAINT content_items_produced_by_check CHECK (((produced_by IS NULL) OR (produced_by = ANY (ARRAY['composer'::text, 'weekly_drafts'::text, 'overnight_agent'::text, 'carousel_studio'::text]))));
ALTER TABLE public.content_items ADD CONSTRAINT content_items_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'published'::text, 'discarded'::text])));
ALTER TABLE public.content_items ADD CONSTRAINT content_items_type_check CHECK ((type = ANY (ARRAY['linkedin_post'::text, 'carousel'::text, 'framework'::text, 'article'::text, 'whitepaper'::text])));
ALTER TABLE public.content_lineage ADD CONSTRAINT content_lineage_content_table_check CHECK ((content_table = ANY (ARRAY['linkedin_posts'::text, 'content_items'::text])));
ALTER TABLE public.content_lineage ADD CONSTRAINT content_lineage_contributor_kind_check CHECK ((contributor_kind = ANY (ARRAY['signal'::text, 'capture'::text, 'evidence_fragment'::text, 'document'::text, 'trend'::text, 'voice_profile'::text])));
ALTER TABLE public.content_lineage ADD CONSTRAINT content_lineage_role_check CHECK ((role = ANY (ARRAY['topic'::text, 'evidence'::text, 'number'::text, 'background'::text, 'timing'::text, 'voice'::text])));
ALTER TABLE public.decisions ADD CONSTRAINT decisions_open_is_falsifiable CHECK (((status <> 'open'::text) OR ((review_on IS NOT NULL) AND (metric_key IS NOT NULL) AND ((metric_key = 'none'::text) OR (expected_value IS NOT NULL)))));
ALTER TABLE public.decisions ADD CONSTRAINT decisions_status_valid CHECK ((status = ANY (ARRAY['pending'::text, 'open'::text, 'confirmed'::text, 'refuted'::text, 'inconclusive'::text])));
ALTER TABLE public.deck_events ADD CONSTRAINT deck_events_event_check CHECK ((event = ANY (ARRAY['generated'::text, 'validation_failed'::text, 'rendered'::text, 'exported'::text, 'export_failed'::text, 'published'::text, 'publish_failed'::text, 'abandoned'::text, 'error'::text])));
ALTER TABLE public.desk_answer_feedback ADD CONSTRAINT desk_answer_feedback_verdict_check CHECK ((verdict = ANY (ARRAY['yes'::text, 'no'::text])));
ALTER TABLE public.desk_eval_runs ADD CONSTRAINT desk_eval_runs_verdict_check CHECK ((verdict = ANY (ARRAY['pass'::text, 'fail'::text, 'partial'::text])));
ALTER TABLE public.desk_learning ADD CONSTRAINT desk_learning_confidence_check CHECK ((confidence = ANY (ARRAY['observed'::text, 'strong'::text])));
ALTER TABLE public.desk_learning ADD CONSTRAINT desk_learning_kind_check CHECK ((kind = ANY (ARRAY['asks_about'::text, 'acts_on'::text, 'rejects'::text, 'talks_like'::text, 'corrects'::text])));
ALTER TABLE public.desk_number_violations ADD CONSTRAINT desk_number_violations_resolved_check CHECK ((resolved = ANY (ARRAY['retry_fixed'::text, 'sentence_dropped'::text])));
ALTER TABLE public.diagnostic_profiles ADD CONSTRAINT diagnostic_profiles_band_source_chk CHECK (((band_source IS NULL) OR (band_source = ANY (ARRAY['detected'::text, 'confirmed'::text, 'corrected'::text]))));
ALTER TABLE public.diagnostic_profiles ADD CONSTRAINT diagnostic_profiles_composer_sort_pref_check CHECK (((composer_sort_pref IS NULL) OR (composer_sort_pref = ANY (ARRAY['recommended'::text, 'newest'::text, 'most_evidence'::text, 'never_written'::text]))));
ALTER TABLE public.diagnostic_profiles ADD CONSTRAINT diagnostic_profiles_exclusion_needs_reason CHECK (((account_type = 'customer'::account_type) OR (excluded_reason IS NOT NULL)));
ALTER TABLE public.diagnostic_profiles ADD CONSTRAINT diagnostic_profiles_theme_preference_check CHECK ((theme_preference = ANY (ARRAY['nebula'::text, 'prism'::text, 'terrain'::text])));
ALTER TABLE public.diagnostic_profiles ADD CONSTRAINT diagnostic_profiles_tier_check CHECK ((tier = ANY (ARRAY['read'::text, 'loop'::text])));
ALTER TABLE public.documents ADD CONSTRAINT documents_cv_label_check CHECK (((cv_label IS NULL) OR (cv_label = ANY (ARRAY['latest'::text, 'best'::text, 'target'::text]))));
ALTER TABLE public.documents ADD CONSTRAINT documents_cv_label_requires_cv_type CHECK (((cv_label IS NULL) OR (document_type = 'cv'::text)));
ALTER TABLE public.documents ADD CONSTRAINT documents_document_type_check CHECK ((document_type = ANY (ARRAY['cv'::text, 'portfolio'::text, 'project'::text, 'testimonial'::text, 'talk'::text, 'other'::text])));
ALTER TABLE public.entries ADD CONSTRAINT entries_type_check CHECK ((type = ANY (ARRAY['link'::text, 'voice'::text, 'text'::text, 'image'::text, 'doc'::text])));
ALTER TABLE public.facet_states ADD CONSTRAINT facet_states_facet_check CHECK ((facet = ANY (ARRAY['identity'::text, 'edge'::text, 'voice'::text, 'focus'::text, 'audience'::text, 'discernment'::text, 'conviction'::text])));
ALTER TABLE public.facet_states ADD CONSTRAINT facet_states_uncertainty_check CHECK (((uncertainty >= (0)::numeric) AND (uncertainty <= (1)::numeric)));
ALTER TABLE public.facet_states ADD CONSTRAINT facet_states_value_check CHECK (((value >= (0)::numeric) AND (value <= (1)::numeric)));
ALTER TABLE public.health_findings ADD CONSTRAINT health_findings_severity_check CHECK ((severity = ANY (ARRAY['critical'::text, 'warn'::text, 'info'::text])));
ALTER TABLE public.home_address ADD CONSTRAINT home_address_lens_check CHECK ((lens = ANY (ARRAY['record'::text, 'room'::text, 'shape'::text])));
ALTER TABLE public.identity_registry ADD CONSTRAINT identity_registry_kind_check CHECK ((kind = ANY (ARRAY['founder'::text, 'qa'::text, 'fixture'::text, 'customer'::text, 'unknown'::text])));
ALTER TABLE public.job_queue ADD CONSTRAINT job_queue_status_chk CHECK ((status = ANY (ARRAY['pending'::text, 'claimed'::text, 'done'::text, 'failed'::text, 'dead'::text])));
ALTER TABLE public.known_issues ADD CONSTRAINT known_issues_severity_check CHECK ((severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])));
ALTER TABLE public.known_issues ADD CONSTRAINT known_issues_status_check CHECK ((status = ANY (ARRAY['open'::text, 'monitoring'::text, 'resolved'::text])));
ALTER TABLE public.linkedin_connections ADD CONSTRAINT linkedin_connections_handle_is_vanity CHECK (((handle IS NULL) OR (handle ~ '^[A-Za-z0-9][A-Za-z0-9-]{1,99}$'::text)));
ALTER TABLE public.linkedin_posts ADD CONSTRAINT linkedin_posts_acquisition_check CHECK ((acquisition = ANY (ARRAY['published_via_aura'::text, 'imported'::text, 'discovered'::text, 'api_synced'::text, 'unset'::text])));
ALTER TABLE public.linkedin_posts ADD CONSTRAINT linkedin_posts_arrived_by_check CHECK ((arrived_by = ANY (ARRAY['published_through_aura'::text, 'imported_by_member'::text, 'discovered_by_search'::text, 'entered_by_member'::text, 'generated_in_place'::text, 'unknown'::text])));
ALTER TABLE public.linkedin_posts ADD CONSTRAINT linkedin_posts_authorship_check CHECK ((authorship = ANY (ARRAY['user_written'::text, 'aura_drafted'::text, 'aura_assisted'::text, 'unknown'::text, 'unset'::text])));
ALTER TABLE public.linkedin_posts ADD CONSTRAINT linkedin_posts_confidence_check CHECK ((confidence = ANY (ARRAY['confirmed'::text, 'reported'::text, 'guessed'::text, 'unknown'::text])));
ALTER TABLE public.linkedin_posts ADD CONSTRAINT linkedin_posts_ending_type_vocab CHECK (((ending_type IS NULL) OR (ending_type = ANY (ARRAY['question'::text, 'suspended'::text, 'reframe'::text, 'equation'::text, 'number'::text, 'cta'::text, 'other'::text]))));
ALTER TABLE public.linkedin_posts ADD CONSTRAINT linkedin_posts_hook_style_vocab CHECK (((hook_style IS NULL) OR (hook_style = ANY (ARRAY['contrarian_claim'::text, 'number_first'::text, 'short_story'::text, 'question'::text, 'experience_led'::text, 'announcement'::text, 'other'::text]))));
ALTER TABLE public.linkedin_posts ADD CONSTRAINT linkedin_posts_made_by_check CHECK ((made_by = ANY (ARRAY['member'::text, 'aura'::text, 'aura_edited_by_member'::text, 'machine'::text, 'unknown'::text])));
ALTER TABLE public.linkedin_posts ADD CONSTRAINT linkedin_posts_produced_by_check CHECK (((produced_by IS NULL) OR (produced_by = ANY (ARRAY['composer'::text, 'weekly_drafts'::text, 'overnight_agent'::text, 'carousel_studio'::text]))));
ALTER TABLE public.linkedin_posts ADD CONSTRAINT linkedin_posts_stance_vocab CHECK (((stance IS NULL) OR (stance = ANY (ARRAY['asserts'::text, 'story'::text, 'teaches'::text, 'doubts'::text, 'analysis'::text]))));
ALTER TABLE public.linkedin_posts ADD CONSTRAINT linkedin_posts_voice_corpus_status_check CHECK ((voice_corpus_status = ANY (ARRAY['included'::text, 'excluded'::text, 'auto_excluded'::text])));
ALTER TABLE public.member_issue_reports ADD CONSTRAINT member_issue_reports_kind_check CHECK ((kind = ANY (ARRAY['crash'::text, 'feedback'::text])));
ALTER TABLE public.metric_targets ADD CONSTRAINT metric_targets_status_ck CHECK ((status = ANY (ARRAY['active'::text, 'kept'::text, 'revised'::text, 'dropped'::text])));
ALTER TABLE public.notification_events ADD CONSTRAINT notification_events_channel_check CHECK ((channel = ANY (ARRAY['inapp'::text, 'email'::text, 'whatsapp'::text, 'push'::text])));
ALTER TABLE public.notification_events ADD CONSTRAINT notification_events_type_check CHECK ((type = ANY (ARRAY['timing_window'::text, 'silence_alarm'::text, 'signal_shift'::text, 'weekly_brief'::text, 'knowledge_debt'::text, 'morning_signal'::text, 'member_reminder'::text])));
ALTER TABLE public.onboarding_questions ADD CONSTRAINT oq_kind_chk CHECK ((kind = ANY (ARRAY['choice'::text, 'multi'::text, 'text'::text, 'proposed'::text])));
ALTER TABLE public.post_events ADD CONSTRAINT post_events_actor_check CHECK ((actor = ANY (ARRAY['aura'::text, 'member'::text, 'system'::text, 'linkedin'::text])));
ALTER TABLE public.post_events ADD CONSTRAINT post_events_event_check CHECK ((event = ANY (ARRAY['drafted'::text, 'edited'::text, 'scheduled'::text, 'publish_attempted'::text, 'published'::text, 'discarded'::text, 'metrics_synced'::text])));
ALTER TABLE public.product_facts ADD CONSTRAINT product_facts_category_check CHECK ((category = ANY (ARRAY['surface'::text, 'score'::text, 'capability'::text, 'limit'::text])));
ALTER TABLE public.profile_copy_drafts ADD CONSTRAINT profile_copy_drafts_target_check CHECK ((target = ANY (ARRAY['headline'::text, 'about'::text])));
ALTER TABLE public.qa_runs ADD CONSTRAINT qa_runs_status_check CHECK ((status = ANY (ARRAY['pass'::text, 'fail'::text, 'warn'::text])));
ALTER TABLE public.signature_events ADD CONSTRAINT signature_events_action_check CHECK ((action = ANY (ARRAY['suggested'::text, 'picked'::text, 'edited'::text, 'exported'::text, 'published'::text])));
ALTER TABLE public.strategic_signals ADD CONSTRAINT strategic_signals_velocity_status_check CHECK ((velocity_status = ANY (ARRAY['accelerating'::text, 'stable'::text, 'fading'::text, 'dormant'::text])));
ALTER TABLE public.voice_feedback ADD CONSTRAINT voice_feedback_verdict_check CHECK ((verdict = ANY (ARRAY['sounds_like_me'::text, 'partly'::text, 'not_me'::text, 'too_formal'::text, 'too_generic'::text, 'too_aggressive'::text, 'would_never_say'::text])));
ALTER TABLE public.voice_post_outcomes ADD CONSTRAINT voice_post_outcomes_outcome_source_check CHECK (((outcome_source IS NULL) OR (outcome_source = ANY (ARRAY['metrics_snapshot'::text, 'post_counts'::text]))));
ALTER TABLE public.voice_rules ADD CONSTRAINT voice_rules_check_shape CHECK ((("check" IS NULL) OR ((jsonb_typeof("check") = 'object'::text) AND (("check" ->> 'kind'::text) = ANY (ARRAY['phrase'::text, 'opening'::text, 'ending'::text, 'marker'::text])) AND (length(btrim(COALESCE(("check" ->> 'value'::text), ''::text))) > 0))));
ALTER TABLE public.voice_rules ADD CONSTRAINT voice_rules_kind_check CHECK ((kind = ANY (ARRAY['always'::text, 'never'::text, 'anchor'::text])));
ALTER TABLE public.voice_rules ADD CONSTRAINT voice_rules_source_check CHECK ((source = ANY (ARRAY['learned'::text, 'user'::text, 'aura'::text])));
ALTER TABLE public.voice_rules ADD CONSTRAINT voice_rules_status_check CHECK ((status = ANY (ARRAY['suggested'::text, 'active'::text, 'dismissed'::text])));
ALTER TABLE public.voice_trait_registry ADD CONSTRAINT voice_trait_registry_group_key_check CHECK ((group_key = ANY (ARRAY['sound'::text, 'structure'::text, 'language'::text])));
ALTER TABLE public.voice_traits ADD CONSTRAINT voice_traits_confidence_check CHECK ((confidence = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])));
ALTER TABLE public.voice_traits ADD CONSTRAINT voice_traits_source_check CHECK ((source = ANY (ARRAY['learned'::text, 'user'::text, 'aura'::text])));
ALTER TABLE public.voice_traits ADD CONSTRAINT voice_traits_value_check CHECK (((value >= (0)::numeric) AND (value <= (100)::numeric)));
ALTER TABLE public.weekly_missions ADD CONSTRAINT weekly_missions_mission_type_check CHECK ((mission_type = ANY (ARRAY['signal'::text, 'content'::text, 'rhythm'::text, 'voice'::text, 'baseline'::text])));
ALTER TABLE public.weekly_missions ADD CONSTRAINT weekly_missions_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'completed'::text, 'expired'::text])));
ALTER TABLE public.whatsapp_links ADD CONSTRAINT whatsapp_links_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'active'::text])));
ALTER TABLE public.agent_findings ADD CONSTRAINT agent_findings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.ai_usage_log ADD CONSTRAINT ai_usage_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.assessment_sessions ADD CONSTRAINT assessment_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.audience_demographics ADD CONSTRAINT audience_demographics_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.audience_insights ADD CONSTRAINT audience_insights_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.aura_conversation_memory ADD CONSTRAINT aura_conversation_memory_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.authority_scores ADD CONSTRAINT authority_scores_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.authority_voice_profiles ADD CONSTRAINT authority_voice_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.beta_allowlist ADD CONSTRAINT beta_allowlist_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.beta_allowlist ADD CONSTRAINT beta_allowlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.beta_feedback ADD CONSTRAINT beta_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.capability_radar_snapshots ADD CONSTRAINT capability_radar_snapshots_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.capability_responses ADD CONSTRAINT capability_responses_dimension_id_fkey FOREIGN KEY (dimension_id) REFERENCES capability_dimensions(id) ON DELETE CASCADE;
ALTER TABLE public.capability_responses ADD CONSTRAINT capability_responses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.captures ADD CONSTRAINT captures_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.chat_conversations ADD CONSTRAINT chat_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.chat_messages ADD CONSTRAINT chat_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES chat_conversations(id) ON DELETE CASCADE;
ALTER TABLE public.chat_messages ADD CONSTRAINT chat_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.content_gate_results ADD CONSTRAINT content_gate_results_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.content_items ADD CONSTRAINT content_items_signal_id_fkey FOREIGN KEY (signal_id) REFERENCES strategic_signals(id) ON DELETE SET NULL;
ALTER TABLE public.content_items ADD CONSTRAINT content_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.deck_events ADD CONSTRAINT deck_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.design_system ADD CONSTRAINT design_system_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.desk_eval_runs ADD CONSTRAINT desk_eval_runs_question_id_fkey FOREIGN KEY (question_id) REFERENCES desk_eval_questions(id) ON DELETE CASCADE;
ALTER TABLE public.diagnostic_profiles ADD CONSTRAINT diagnostic_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.discovery_review_queue ADD CONSTRAINT discovery_review_queue_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.document_briefs ADD CONSTRAINT document_briefs_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE;
ALTER TABLE public.document_chunks ADD CONSTRAINT document_chunks_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE;
ALTER TABLE public.document_chunks ADD CONSTRAINT document_chunks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.document_jobs ADD CONSTRAINT document_jobs_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE;
ALTER TABLE public.document_jobs ADD CONSTRAINT document_jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.documents ADD CONSTRAINT documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.draft_edits ADD CONSTRAINT draft_edits_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.ef_error_log ADD CONSTRAINT ef_error_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.entries ADD CONSTRAINT entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.eval_metrics ADD CONSTRAINT eval_metrics_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.evidence_fragments ADD CONSTRAINT evidence_fragments_source_registry_id_fkey FOREIGN KEY (source_registry_id) REFERENCES source_registry(id) ON DELETE CASCADE;
ALTER TABLE public.evidence_fragments ADD CONSTRAINT evidence_fragments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.evidence_jobs ADD CONSTRAINT evidence_jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.facet_states ADD CONSTRAINT facet_states_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.focus_accounts ADD CONSTRAINT focus_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.framework_activations ADD CONSTRAINT framework_activations_framework_id_fkey FOREIGN KEY (framework_id) REFERENCES master_frameworks(id) ON DELETE CASCADE;
ALTER TABLE public.framework_activations ADD CONSTRAINT framework_activations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.home_address ADD CONSTRAINT home_address_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.identity_registry ADD CONSTRAINT identity_registry_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.impact_narratives ADD CONSTRAINT impact_narratives_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.import_jobs ADD CONSTRAINT import_jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.imprint_snapshots ADD CONSTRAINT imprint_snapshots_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.industry_trends ADD CONSTRAINT industry_trends_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.influence_snapshots ADD CONSTRAINT influence_snapshots_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.instrument_runs ADD CONSTRAINT instrument_runs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.job_queue ADD CONSTRAINT job_queue_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.learned_intelligence ADD CONSTRAINT learned_intelligence_source_document_id_fkey FOREIGN KEY (source_document_id) REFERENCES documents(id) ON DELETE SET NULL;
ALTER TABLE public.learned_intelligence ADD CONSTRAINT learned_intelligence_source_entry_id_fkey FOREIGN KEY (source_entry_id) REFERENCES entries(id) ON DELETE SET NULL;
ALTER TABLE public.learned_intelligence ADD CONSTRAINT learned_intelligence_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.lifecycle_email_log ADD CONSTRAINT lifecycle_email_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.lifecycle_emails ADD CONSTRAINT lifecycle_emails_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.linkedin_connections ADD CONSTRAINT linkedin_connections_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.linkedin_post_metrics ADD CONSTRAINT linkedin_post_metrics_post_id_fkey FOREIGN KEY (post_id) REFERENCES linkedin_posts(id) ON DELETE CASCADE;
ALTER TABLE public.linkedin_post_metrics ADD CONSTRAINT linkedin_post_metrics_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.linkedin_posts ADD CONSTRAINT linkedin_posts_source_signal_id_fkey FOREIGN KEY (source_signal_id) REFERENCES strategic_signals(id);
ALTER TABLE public.linkedin_posts ADD CONSTRAINT linkedin_posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.linkedin_profile_snapshots ADD CONSTRAINT linkedin_profile_snapshots_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.market_mirror_cache ADD CONSTRAINT market_mirror_cache_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.master_frameworks ADD CONSTRAINT master_frameworks_entry_id_fkey FOREIGN KEY (entry_id) REFERENCES entries(id) ON DELETE SET NULL;
ALTER TABLE public.master_frameworks ADD CONSTRAINT master_frameworks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.member_issue_reports ADD CONSTRAINT member_issue_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.narrative_suggestions ADD CONSTRAINT narrative_suggestions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.notification_events ADD CONSTRAINT notification_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.onboarding_article_log ADD CONSTRAINT onboarding_article_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.operation_runs ADD CONSTRAINT operation_runs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.output_leak_log ADD CONSTRAINT output_leak_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.post_events ADD CONSTRAINT post_events_post_id_fkey FOREIGN KEY (post_id) REFERENCES linkedin_posts(id) ON DELETE CASCADE;
ALTER TABLE public.post_events ADD CONSTRAINT post_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.product_events ADD CONSTRAINT product_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.profile_copy_drafts ADD CONSTRAINT profile_copy_drafts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.qa_audit_results ADD CONSTRAINT qa_audit_results_run_by_fkey FOREIGN KEY (run_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.report_shares ADD CONSTRAINT report_shares_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.report_snapshots ADD CONSTRAINT report_snapshots_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.score_snapshots ADD CONSTRAINT score_snapshots_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.signal_engagements ADD CONSTRAINT signal_engagements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.signal_topic_preferences ADD CONSTRAINT signal_topic_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.signature_events ADD CONSTRAINT signature_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.skill_targets ADD CONSTRAINT skill_targets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.source_events ADD CONSTRAINT source_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.source_registry ADD CONSTRAINT source_registry_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.strategic_signals ADD CONSTRAINT strategic_signals_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.sync_errors ADD CONSTRAINT sync_errors_sync_run_id_fkey FOREIGN KEY (sync_run_id) REFERENCES sync_runs(id) ON DELETE CASCADE;
ALTER TABLE public.sync_errors ADD CONSTRAINT sync_errors_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.sync_runs ADD CONSTRAINT sync_runs_account_id_fkey FOREIGN KEY (account_id) REFERENCES linkedin_connections(id) ON DELETE CASCADE;
ALTER TABLE public.sync_runs ADD CONSTRAINT sync_runs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.training_logs ADD CONSTRAINT training_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_milestones ADD CONSTRAINT user_milestones_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_widget_layout ADD CONSTRAINT user_widget_layout_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.voice_distribution ADD CONSTRAINT voice_distribution_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.voice_feedback ADD CONSTRAINT voice_feedback_post_id_fkey FOREIGN KEY (post_id) REFERENCES linkedin_posts(id) ON DELETE SET NULL;
ALTER TABLE public.voice_feedback ADD CONSTRAINT voice_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.voice_learning_prefs ADD CONSTRAINT voice_learning_prefs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.voice_post_outcomes ADD CONSTRAINT voice_post_outcomes_post_id_fkey FOREIGN KEY (post_id) REFERENCES linkedin_posts(id) ON DELETE CASCADE;
ALTER TABLE public.voice_post_outcomes ADD CONSTRAINT voice_post_outcomes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.voice_rules ADD CONSTRAINT voice_rules_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES authority_voice_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.voice_rules ADD CONSTRAINT voice_rules_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.voice_trait_rejections ADD CONSTRAINT voice_trait_rejections_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES authority_voice_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.voice_trait_rejections ADD CONSTRAINT voice_trait_rejections_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.voice_traits ADD CONSTRAINT voice_traits_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES authority_voice_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.voice_traits ADD CONSTRAINT voice_traits_trait_key_fkey FOREIGN KEY (trait_key) REFERENCES voice_trait_registry(trait_key);
ALTER TABLE public.voice_traits ADD CONSTRAINT voice_traits_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.weekly_missions ADD CONSTRAINT weekly_missions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.whatsapp_links ADD CONSTRAINT whatsapp_links_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.whatsapp_messages ADD CONSTRAINT whatsapp_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.widget_slot_votes ADD CONSTRAINT widget_slot_votes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

CREATE INDEX idx_admin_action_created ON public.admin_action_log USING btree (created_at DESC);
CREATE INDEX idx_admin_action_target ON public.admin_action_log USING btree (target_user_id);
CREATE INDEX agent_findings_user_created_idx ON public.agent_findings USING btree (user_id, created_at DESC);
CREATE INDEX agent_findings_user_status_idx ON public.agent_findings USING btree (user_id, status);
CREATE INDEX idx_ai_usage_created ON public.ai_usage_log USING btree (created_at DESC);
CREATE INDEX idx_ai_usage_function ON public.ai_usage_log USING btree (function_name);
CREATE INDEX idx_ai_usage_provider ON public.ai_usage_log USING btree (provider);
CREATE INDEX idx_ai_usage_user ON public.ai_usage_log USING btree (user_id);
CREATE INDEX idx_asess_expiry ON public.assessment_sessions USING btree (expires_at) WHERE (user_id IS NULL);
CREATE INDEX idx_asess_ip ON public.assessment_sessions USING btree (ip_hash, created_at);
CREATE INDEX idx_asess_token ON public.assessment_sessions USING btree (token);
CREATE INDEX idx_audience_demographics_user_cat ON public.audience_demographics USING btree (user_id, category);
CREATE INDEX idx_audience_insights_user ON public.audience_insights USING btree (user_id);
CREATE INDEX idx_acm_summary_recent ON public.aura_conversation_memory USING btree (user_id, created_at DESC) WHERE (role IS NULL);
CREATE INDEX idx_acm_user_created ON public.aura_conversation_memory USING btree (user_id, created_at DESC);
CREATE INDEX idx_acm_user_date ON public.aura_conversation_memory USING btree (user_id, session_date DESC);
CREATE UNIQUE INDEX uq_acm_summary_session ON public.aura_conversation_memory USING btree (user_id, session_id) WHERE (role IS NULL);
CREATE UNIQUE INDEX authority_voice_profiles_one_primary ON public.authority_voice_profiles USING btree (user_id) WHERE is_primary;
CREATE UNIQUE INDEX authority_voice_profiles_one_primary_per_user_idx ON public.authority_voice_profiles USING btree (user_id) WHERE (is_primary = true);
CREATE UNIQUE INDEX authority_voice_profiles_one_primary_uq ON public.authority_voice_profiles USING btree (user_id) WHERE is_primary;
CREATE UNIQUE INDEX authority_voice_profiles_user_mode_lang_uq ON public.authority_voice_profiles USING btree (user_id, mode_key, language) WHERE (mode_key IS NOT NULL);
CREATE INDEX idx_beta_allowlist_email ON public.beta_allowlist USING btree (email);
CREATE INDEX idx_beta_allowlist_invited_by ON public.beta_allowlist USING btree (invited_by);
CREATE INDEX idx_beta_allowlist_status ON public.beta_allowlist USING btree (status);
CREATE INDEX idx_beta_allowlist_user ON public.beta_allowlist USING btree (user_id);
CREATE INDEX idx_beta_feedback_user ON public.beta_feedback USING btree (user_id);
CREATE UNIQUE INDEX capability_dimensions_key ON public.capability_dimensions USING btree (band, COALESCE(sector, '*'::text), "position");
CREATE INDEX idx_capability_radar_snapshots_user ON public.capability_radar_snapshots USING btree (user_id, taken_at DESC);
CREATE INDEX idx_capability_responses_user ON public.capability_responses USING btree (user_id, answered_at DESC);
CREATE INDEX idx_captures_source_url ON public.captures USING btree (source_url);
CREATE INDEX idx_captures_user_id ON public.captures USING btree (user_id);
CREATE INDEX idx_chat_conversations_user ON public.chat_conversations USING btree (user_id);
CREATE INDEX idx_chat_messages_conversation ON public.chat_messages USING btree (conversation_id);
CREATE INDEX idx_chat_messages_created ON public.chat_messages USING btree (created_at);
CREATE INDEX idx_chat_messages_user ON public.chat_messages USING btree (user_id);
CREATE INDEX contact_messages_created_idx ON public.contact_messages USING btree (created_at DESC);
CREATE INDEX contact_messages_email_created_idx ON public.contact_messages USING btree (email, created_at DESC);
CREATE INDEX content_gate_results_content_hash_idx ON public.content_gate_results USING btree (content_hash);
CREATE INDEX idx_content_gate_results_user_created ON public.content_gate_results USING btree (user_id, created_at DESC);
CREATE INDEX content_items_user_made_by_created_idx ON public.content_items USING btree (user_id, made_by, created_at DESC);
CREATE INDEX content_items_user_made_created_idx ON public.content_items USING btree (user_id, made_by, created_at DESC);
CREATE INDEX idx_content_items_embedding ON public.content_items USING hnsw (embedding vector_cosine_ops);
CREATE INDEX idx_content_items_signal ON public.content_items USING btree (signal_id);
CREATE INDEX idx_content_items_tsv_col ON public.content_items USING gin (tsv);
CREATE INDEX idx_content_items_user ON public.content_items USING btree (user_id);
CREATE INDEX content_lineage_content_idx ON public.content_lineage USING btree (content_table, content_id);
CREATE UNIQUE INDEX content_lineage_unique ON public.content_lineage USING btree (content_table, content_id, contributor_kind, contributor_id, role);
CREATE INDEX decisions_review_idx ON public.decisions USING btree (status, review_on);
CREATE INDEX deck_events_user_created_idx ON public.deck_events USING btree (user_id, created_at DESC);
CREATE INDEX decks_user_id_created_at_idx ON public.decks USING btree (user_id, created_at DESC);
CREATE UNIQUE INDEX idx_design_system_active_scope ON public.design_system USING btree (scope) WHERE (is_active = true);
CREATE INDEX idx_design_system_created_by ON public.design_system USING btree (created_by);
CREATE INDEX idx_desk_answer_feedback_user ON public.desk_answer_feedback USING btree (user_id, created_at DESC);
CREATE INDEX desk_eval_questions_set_idx ON public.desk_eval_questions USING btree (question_set, active);
CREATE INDEX desk_eval_runs_question_idx ON public.desk_eval_runs USING btree (question_id, run_at DESC);
CREATE INDEX idx_desk_learning_user ON public.desk_learning USING btree (user_id, dismissed, evidence_count DESC);
CREATE INDEX desk_number_violations_run_at_idx ON public.desk_number_violations USING btree (run_at DESC);
CREATE INDEX diagnostic_profiles_tier_idx ON public.diagnostic_profiles USING btree (tier);
CREATE UNIQUE INDEX idx_review_queue_url_user ON public.discovery_review_queue USING btree (user_id, candidate_url);
CREATE INDEX idx_document_briefs_document ON public.document_briefs USING btree (document_id);
CREATE INDEX idx_document_briefs_embedding ON public.document_briefs USING hnsw (embedding vector_cosine_ops);
CREATE INDEX idx_document_briefs_tsv ON public.document_briefs USING gin (tsv);
CREATE INDEX idx_document_briefs_user ON public.document_briefs USING btree (user_id);
CREATE INDEX document_chunks_embedding_idx ON public.document_chunks USING hnsw (embedding vector_cosine_ops);
CREATE INDEX idx_document_chunks_document ON public.document_chunks USING btree (document_id);
CREATE INDEX idx_document_chunks_tsv ON public.document_chunks USING gin (tsv);
CREATE INDEX idx_document_chunks_user ON public.document_chunks USING btree (user_id);
CREATE INDEX document_jobs_document_id_idx ON public.document_jobs USING btree (document_id);
CREATE INDEX document_jobs_stage_heartbeat_idx ON public.document_jobs USING btree (stage, last_heartbeat);
CREATE INDEX documents_status_processing_started_at_idx ON public.documents USING btree (status, processing_started_at) WHERE (status = 'processing'::text);
CREATE INDEX idx_documents_user ON public.documents USING btree (user_id);
CREATE INDEX idx_draft_edits_user_created ON public.draft_edits USING btree (user_id, created_at DESC);
CREATE INDEX idx_ef_error_created ON public.ef_error_log USING btree (created_at DESC);
CREATE INDEX idx_ef_error_fn ON public.ef_error_log USING btree (function_name);
CREATE INDEX idx_ef_error_severity_created ON public.ef_error_log USING btree (severity, created_at DESC);
CREATE INDEX ef_event_log_created_at_idx ON public.ef_event_log_retired_20260724 USING btree (created_at DESC);
CREATE INDEX ef_event_log_function_name_idx ON public.ef_event_log_retired_20260724 USING btree (function_name);
CREATE INDEX entries_embedding_idx ON public.entries USING hnsw (embedding vector_cosine_ops);
CREATE UNIQUE INDEX entries_user_url_unique ON public.entries USING btree (user_id, image_url) WHERE (image_url IS NOT NULL);
CREATE INDEX idx_entries_tsv ON public.entries USING gin (tsv);
CREATE INDEX idx_entries_user_created ON public.entries USING btree (user_id, created_at DESC);
CREATE INDEX eval_metrics_metric_measured_idx ON public.eval_metrics USING btree (metric, measured_at DESC);
CREATE INDEX eval_metrics_user_measured_idx ON public.eval_metrics USING btree (user_id, measured_at DESC);
CREATE INDEX idx_evidence_fragments_embedding ON public.evidence_fragments USING hnsw (embedding vector_cosine_ops);
CREATE INDEX idx_evidence_fragments_pipeline_version ON public.evidence_fragments USING btree (pipeline_version);
CREATE INDEX idx_evidence_fragments_source ON public.evidence_fragments USING btree (source_registry_id);
CREATE INDEX idx_evidence_fragments_tsv ON public.evidence_fragments USING gin (tsv);
CREATE INDEX idx_evidence_fragments_type ON public.evidence_fragments USING btree (fragment_type);
CREATE INDEX idx_evidence_fragments_user ON public.evidence_fragments USING btree (user_id);
CREATE INDEX evidence_jobs_source_registry_idx ON public.evidence_jobs USING btree (source_registry_id);
CREATE INDEX evidence_jobs_status_heartbeat_idx ON public.evidence_jobs USING btree (status, last_heartbeat);
CREATE INDEX idx_framework_activations_framework ON public.framework_activations USING btree (framework_id);
CREATE INDEX idx_framework_activations_user ON public.framework_activations USING btree (user_id);
CREATE INDEX guide_articles_tab_sort_idx ON public.guide_articles USING btree (tab, sort_order);
CREATE INDEX health_findings_last_seen_idx ON public.health_findings USING btree (last_seen DESC);
CREATE UNIQUE INDEX health_findings_open_code_uidx ON public.health_findings USING btree (code) WHERE (resolved_at IS NULL);
CREATE INDEX home_address_user_date_idx ON public.home_address USING btree (user_id, address_date DESC);
CREATE INDEX identity_registry_kind_idx ON public.identity_registry USING btree (kind);
CREATE INDEX idx_impact_narratives_user ON public.impact_narratives USING btree (user_id);
CREATE INDEX idx_import_jobs_user ON public.import_jobs USING btree (user_id);
CREATE INDEX imprint_snapshots_user_created_idx ON public.imprint_snapshots USING btree (user_id, created_at DESC);
CREATE INDEX idx_industry_trends_canonical_url ON public.industry_trends USING btree (user_id, canonical_url);
CREATE INDEX idx_industry_trends_final_score ON public.industry_trends USING btree (user_id, final_score DESC, fetched_at DESC);
CREATE INDEX idx_industry_trends_user_status_fetched ON public.industry_trends USING btree (user_id, status, fetched_at DESC);
CREATE INDEX idx_industry_trends_user_valid_score ON public.industry_trends USING btree (user_id, is_valid, final_score DESC);
CREATE INDEX idx_industry_trends_validation_score ON public.industry_trends USING btree (user_id, validation_score DESC, fetched_at DESC);
CREATE INDEX instrument_runs_created_idx ON public.instrument_runs USING btree (created_at);
CREATE INDEX instrument_runs_user_idx ON public.instrument_runs USING btree (user_id);
CREATE INDEX job_queue_claimable ON public.job_queue USING btree (job_type, status, priority DESC, scheduled_for);
CREATE UNIQUE INDEX job_queue_one_live ON public.job_queue USING btree (job_type, user_id) WHERE (status = ANY (ARRAY['pending'::text, 'claimed'::text]));
CREATE INDEX known_issues_status_severity_idx ON public.known_issues USING btree (status, severity);
CREATE INDEX idx_learned_intel_src_doc ON public.learned_intelligence USING btree (source_document_id);
CREATE INDEX idx_learned_intel_src_entry ON public.learned_intelligence USING btree (source_entry_id);
CREATE INDEX idx_learned_intel_user ON public.learned_intelligence USING btree (user_id);
CREATE INDEX idx_lifecycle_email_log_user ON public.lifecycle_email_log USING btree (user_id, message_key);
CREATE INDEX idx_lifecycle_emails_user ON public.lifecycle_emails USING btree (user_id);
CREATE UNIQUE INDEX linkedin_connections_user_id_idx ON public.linkedin_connections USING btree (user_id);
CREATE INDEX idx_li_post_metrics_user ON public.linkedin_post_metrics USING btree (user_id);
CREATE UNIQUE INDEX idx_linkedin_posts_canonical_url ON public.linkedin_posts USING btree (user_id, post_url) WHERE (post_url IS NOT NULL);
CREATE INDEX idx_linkedin_posts_corpus ON public.linkedin_posts USING btree (user_id, voice_corpus_status);
CREATE INDEX idx_linkedin_posts_embedding ON public.linkedin_posts USING hnsw (embedding vector_cosine_ops);
CREATE INDEX idx_linkedin_posts_published_at ON public.linkedin_posts USING btree (user_id, published_at DESC);
CREATE INDEX idx_linkedin_posts_publishing_claimed ON public.linkedin_posts USING btree (claimed_at) WHERE (tracking_status = 'publishing'::text);
CREATE INDEX idx_linkedin_posts_source_signal_id ON public.linkedin_posts USING btree (source_signal_id) WHERE (source_signal_id IS NOT NULL);
CREATE INDEX idx_linkedin_posts_tsv_col ON public.linkedin_posts USING gin (tsv);
CREATE INDEX idx_linkedin_posts_user_id ON public.linkedin_posts USING btree (user_id);
CREATE INDEX linkedin_posts_acquisition_idx ON public.linkedin_posts USING btree (user_id, acquisition);
CREATE INDEX linkedin_posts_authorship_idx ON public.linkedin_posts USING btree (user_id, authorship);
CREATE INDEX linkedin_profile_snapshots_user_fetched ON public.linkedin_profile_snapshots USING btree (user_id, fetched_at);
CREATE INDEX linkedin_profile_snapshots_user_fetched_desc ON public.linkedin_profile_snapshots USING btree (user_id, fetched_at DESC);
CREATE INDEX idx_master_frameworks_entry ON public.master_frameworks USING btree (entry_id);
CREATE INDEX idx_master_frameworks_user ON public.master_frameworks USING btree (user_id);
CREATE INDEX member_issue_reports_created_idx ON public.member_issue_reports USING btree (created_at DESC);
CREATE INDEX metric_targets_metric_idx ON public.metric_targets USING btree (metric_key, status, set_on DESC);
CREATE INDEX mirror_requests_ip_time ON public.mirror_requests USING btree (ip_hash, created_at DESC);
CREATE INDEX idx_narrative_sugg_user ON public.narrative_suggestions USING btree (user_id);
CREATE INDEX idx_ne_user_unread ON public.notification_events USING btree (user_id, read, sent_at DESC);
CREATE INDEX idx_notifications_user_read ON public.notifications USING btree (user_id, created_at DESC);
CREATE INDEX idx_onboarding_article_log_created_at ON public.onboarding_article_log USING btree (created_at DESC);
CREATE UNIQUE INDEX onboarding_questions_key ON public.onboarding_questions USING btree (band, COALESCE(sector, '*'::text), "position");
CREATE INDEX operation_runs_operation_started_idx ON public.operation_runs USING btree (operation, started_at DESC);
CREATE INDEX operation_runs_outcome_idx ON public.operation_runs USING btree (outcome);
CREATE INDEX ops_alerts_created_idx ON public.ops_alerts USING btree (created_at DESC);
CREATE INDEX ops_alerts_open_source_idx ON public.ops_alerts USING btree (source) WHERE (status = 'open'::text);
CREATE INDEX ops_alerts_source_created_idx ON public.ops_alerts USING btree (source, created_at DESC);
CREATE INDEX idx_output_leak_log_created_at ON public.output_leak_log USING btree (created_at DESC);
CREATE INDEX idx_output_leak_log_stage ON public.output_leak_log USING btree (leak_stage, created_at DESC);
CREATE INDEX post_events_post_idx ON public.post_events USING btree (post_id);
CREATE INDEX post_events_user_at_idx ON public.post_events USING btree (user_id, at DESC);
CREATE INDEX product_events_event_time_idx ON public.product_events USING btree (event, occurred_at DESC);
CREATE INDEX product_events_user_time_idx ON public.product_events USING btree (user_id, occurred_at DESC);
CREATE INDEX idx_qa_audit_run_at ON public.qa_audit_results USING btree (run_at DESC);
CREATE INDEX idx_qa_audit_run_by ON public.qa_audit_results USING btree (run_by);
CREATE INDEX qa_runs_check_key_idx ON public.qa_runs USING btree (check_key);
CREATE INDEX qa_runs_run_at_idx ON public.qa_runs USING btree (run_at DESC);
CREATE INDEX read_queue_notified_idx ON public.read_queue USING btree (notified_at);
CREATE INDEX read_queue_requested_at_idx ON public.read_queue USING btree (requested_at);
CREATE INDEX report_shares_user_idx ON public.report_shares USING btree (user_id);
CREATE UNIQUE INDEX report_snapshots_one_current_per_user ON public.report_snapshots USING btree (user_id) WHERE is_current;
CREATE INDEX report_snapshots_user_version_idx ON public.report_snapshots USING btree (user_id, version DESC);
CREATE UNIQUE INDEX report_snapshots_user_version_uniq ON public.report_snapshots USING btree (user_id, version);
CREATE INDEX request_snapshots_requested_at_idx ON public.request_snapshots USING btree (requested_at DESC);
CREATE INDEX idx_retrieval_logs_user_created ON public.retrieval_logs USING btree (user_id, created_at DESC);
CREATE INDEX idx_score_snapshots_user ON public.score_snapshots USING btree (user_id, created_at DESC);
CREATE INDEX ship_markers_shipped_on_idx ON public.ship_markers USING btree (shipped_on);
CREATE INDEX signature_events_user_created_idx ON public.signature_events USING btree (user_id, created_at DESC);
CREATE INDEX signup_attempts_ip_idx ON public.signup_attempts USING btree (ip_hash, created_at);
CREATE INDEX signup_refusals_ip_idx ON public.signup_refusals USING btree (ip_hash, created_at);
CREATE INDEX source_events_user_occurred_idx ON public.source_events USING btree (user_id, occurred_at DESC);
CREATE INDEX source_events_user_unprocessed_idx ON public.source_events USING btree (user_id, processed_at) WHERE (processed_at IS NULL);
CREATE INDEX idx_source_registry_signal_status ON public.source_registry USING btree (processed, signal_status, processed_at);
CREATE INDEX idx_source_registry_source ON public.source_registry USING btree (source_type, source_id);
CREATE INDEX idx_source_registry_user_processed ON public.source_registry USING btree (user_id, processed);
CREATE INDEX idx_strategic_signals_embedding ON public.strategic_signals USING hnsw (embedding vector_cosine_ops);
CREATE INDEX idx_strategic_signals_tsv ON public.strategic_signals USING gin (to_tsvector('english'::regconfig, ((((COALESCE(signal_title, ''::text) || ' '::text) || COALESCE(explanation, ''::text)) || ' '::text) || COALESCE(strategic_implications, ''::text))));
CREATE INDEX idx_strategic_signals_tsv_col ON public.strategic_signals USING gin (tsv);
CREATE INDEX idx_strategic_signals_user_created ON public.strategic_signals USING btree (user_id, created_at DESC);
CREATE INDEX idx_strategic_signals_user_status ON public.strategic_signals USING btree (user_id, status, priority_score DESC);
CREATE INDEX idx_sync_errors_run ON public.sync_errors USING btree (sync_run_id);
CREATE INDEX idx_sync_runs_account ON public.sync_runs USING btree (account_id);
CREATE INDEX idx_user_milestones_user ON public.user_milestones USING btree (user_id);
CREATE INDEX voice_feedback_user_id_idx ON public.voice_feedback USING btree (user_id);
CREATE INDEX voice_post_outcomes_user_idx ON public.voice_post_outcomes USING btree (user_id, published_at DESC);
CREATE INDEX voice_rules_user_kind_idx ON public.voice_rules USING btree (user_id, kind, rank);
CREATE INDEX voice_rules_user_status_idx ON public.voice_rules USING btree (user_id, status);
CREATE INDEX voice_trait_rejections_lookup_idx ON public.voice_trait_rejections USING btree (profile_id, trait_key, rejected_until);
CREATE INDEX voice_traits_user_id_idx ON public.voice_traits USING btree (user_id);
CREATE INDEX idx_weekly_missions_user_status ON public.weekly_missions USING btree (user_id, status);
CREATE INDEX idx_whatsapp_messages_created_at ON public.whatsapp_messages USING btree (created_at DESC);
CREATE INDEX idx_whatsapp_messages_user ON public.whatsapp_messages USING btree (user_id);
