-- 06 — triggers.
CREATE TRIGGER update_beta_allowlist_updated_at BEFORE UPDATE ON public.beta_allowlist FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER capability_responses_touch BEFORE INSERT OR UPDATE ON public.capability_responses FOR EACH ROW EXECUTE FUNCTION touch_capability_response();
CREATE TRIGGER set_updated_at_chat_conversations BEFORE UPDATE ON public.chat_conversations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER content_items_tsv_update BEFORE INSERT OR UPDATE ON public.content_items FOR EACH ROW EXECUTE FUNCTION content_items_tsv_trigger();
CREATE TRIGGER update_content_items_updated_at BEFORE UPDATE ON public.content_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER daily_brief_snapshots_no_mutation BEFORE DELETE OR UPDATE ON public.daily_brief_snapshots FOR EACH ROW EXECUTE FUNCTION daily_brief_snapshots_immutable();
CREATE TRIGGER decks_set_updated_at BEFORE UPDATE ON public.decks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER desk_learning_updated_at BEFORE UPDATE ON public.desk_learning FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER diagnostic_profiles_guard_billing BEFORE UPDATE ON public.diagnostic_profiles FOR EACH ROW EXECUTE FUNCTION guard_profile_billing_columns();
CREATE TRIGGER grant_member_role_on_profile_trigger AFTER INSERT ON public.diagnostic_profiles FOR EACH ROW EXECUTE FUNCTION grant_member_role_on_profile();
CREATE TRIGGER guard_account_type_changes BEFORE UPDATE ON public.diagnostic_profiles FOR EACH ROW EXECUTE FUNCTION guard_account_type_changes();
CREATE TRIGGER sync_tier_from_plan BEFORE INSERT OR UPDATE OF plan ON public.diagnostic_profiles FOR EACH ROW EXECUTE FUNCTION sync_tier_from_plan();
CREATE TRIGGER document_briefs_tsv_update BEFORE INSERT OR UPDATE ON public.document_briefs FOR EACH ROW EXECUTE FUNCTION document_briefs_tsv_trigger();
CREATE TRIGGER update_entries_updated_at BEFORE UPDATE ON public.entries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER evidence_fragments_tsv_update BEFORE INSERT OR UPDATE ON public.evidence_fragments FOR EACH ROW EXECUTE FUNCTION evidence_fragments_tsv_trigger();
CREATE TRIGGER facet_states_set_updated_at BEFORE UPDATE ON public.facet_states FOR EACH ROW EXECUTE FUNCTION set_updated_at_facet_states();
CREATE TRIGGER update_guide_articles_updated_at BEFORE UPDATE ON public.guide_articles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_health_findings_updated_at BEFORE UPDATE ON public.health_findings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER job_queue_set_updated_at BEFORE UPDATE ON public.job_queue FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER known_issues_set_updated_at BEFORE UPDATE ON public.known_issues FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER learned_intelligence_tsv_update BEFORE INSERT OR UPDATE ON public.learned_intelligence FOR EACH ROW EXECUTE FUNCTION learned_intelligence_tsv_trigger();
CREATE TRIGGER linkedin_posts_tsv_update BEFORE INSERT OR UPDATE ON public.linkedin_posts FOR EACH ROW EXECUTE FUNCTION linkedin_posts_tsv_trigger();
CREATE TRIGGER trg_linkedin_posts_authorship_guard BEFORE INSERT OR UPDATE ON public.linkedin_posts FOR EACH ROW EXECUTE FUNCTION enforce_published_authorship();
CREATE TRIGGER trg_record_post_event AFTER INSERT OR UPDATE ON public.linkedin_posts FOR EACH ROW EXECUTE FUNCTION record_post_event();
CREATE TRIGGER update_linkedin_profile_snapshots_updated_at BEFORE UPDATE ON public.linkedin_profile_snapshots FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER product_facts_updated_at BEFORE UPDATE ON public.product_facts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_profile_copy_drafts_updated_at BEFORE UPDATE ON public.profile_copy_drafts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_recommended_moves_updated_at BEFORE UPDATE ON public.recommended_moves_retired_20260718 FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_skill_targets_updated_at BEFORE UPDATE ON public.skill_targets FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER strategic_signals_tsv_update BEFORE INSERT OR UPDATE ON public.strategic_signals FOR EACH ROW EXECUTE FUNCTION strategic_signals_tsv_trigger();
CREATE TRIGGER trg_notify_first_signal AFTER INSERT ON public.strategic_signals FOR EACH ROW EXECUTE FUNCTION notify_first_signal();
CREATE TRIGGER update_strategic_signals_updated_at BEFORE UPDATE ON public.strategic_signals FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER theme_aliases_reject_stopword BEFORE INSERT OR UPDATE ON public.theme_aliases FOR EACH ROW EXECUTE FUNCTION reject_stopword_alias();
CREATE TRIGGER update_voice_distribution_updated_at BEFORE UPDATE ON public.voice_distribution FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_voice_learning_prefs_updated_at BEFORE UPDATE ON public.voice_learning_prefs FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_voice_post_outcomes_updated_at BEFORE UPDATE ON public.voice_post_outcomes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER voice_rules_updated_at BEFORE UPDATE ON public.voice_rules FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_voice_traits_updated_at BEFORE UPDATE ON public.voice_traits FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_whatsapp_links_updated_at BEFORE UPDATE ON public.whatsapp_links FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
