// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list-signals.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_signals_default = defineTool({
  name: "list_active_signals",
  title: "List active strategic signals",
  description: "List the signed-in user's active strategic signals from Aura, ordered by confidence.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("How many signals to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("strategic_signals").select("id, signal_title, explanation, strategic_implications, confidence, theme_tags, skill_pillars, fragment_count, status, created_at, updated_at").eq("user_id", ctx.getUserId()).eq("status", "active").order("confidence", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { signals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-signal.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_signal_default = defineTool2({
  name: "get_signal_details",
  title: "Get signal details with evidence",
  description: "Get one Aura strategic signal by id, including its full explanation, strategic implications, and supporting evidence fragments.",
  inputSchema: {
    signal_id: z2.string().uuid().describe("The strategic signal id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ signal_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data: signal, error } = await supabase.from("strategic_signals").select("id, signal_title, explanation, strategic_implications, supporting_evidence_ids, theme_tags, skill_pillars, confidence, fragment_count, framework_opportunity, content_opportunity, status, created_at, updated_at").eq("id", signal_id).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!signal) return { content: [{ type: "text", text: "Signal not found." }], isError: true };
    const evidenceIds = signal.supporting_evidence_ids ?? [];
    let evidence = [];
    if (evidenceIds.length > 0) {
      const { data: frags } = await supabase.from("evidence_fragments").select("id, title, content, source_type, created_at").in("id", evidenceIds).limit(20);
      evidence = frags ?? [];
    }
    const payload = { signal, evidence };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-posts.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_posts_default = defineTool3({
  name: "list_recent_posts",
  title: "List recent LinkedIn posts",
  description: "List the signed-in user's recent LinkedIn posts tracked by Aura (drafts and published), most recent first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("How many posts to return (default 10)."),
    tracking_status: z3.enum(["draft", "published", "scheduled"]).optional().describe("Filter by tracking status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, tracking_status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let query = supabase.from("linkedin_posts").select("id, post_text, format_type, framework_type, tracking_status, published_at, created_at, like_count, comment_count, repost_count, engagement_score, linkedin_url").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (tracking_status) query = query.eq("tracking_status", tracking_status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-capture.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_capture_default = defineTool4({
  name: "create_capture",
  title: "Capture a note into Aura",
  description: "Save a note, article link, or observation into the signed-in user's Aura knowledge base as an entry. Aura uses these captures to detect strategic signals.",
  inputSchema: {
    content: z4.string().min(1).describe("The note text, quote, or article body to capture."),
    title: z4.string().optional().describe("Optional short title for the capture."),
    type: z4.enum(["note", "article", "observation", "quote"]).optional().describe("What kind of capture this is (default note).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ content, title, type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("entries").insert({
      user_id: ctx.getUserId(),
      content,
      title: title ?? null,
      type: type ?? "note"
    }).select("id, title, type, created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Captured entry ${data.id}.` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zddlsztxfzvevzjbuocc";
var mcp_default = defineMcp({
  name: "aura-mcp",
  title: "Aura",
  version: "0.1.0",
  instructions: "Aura is a strategic intelligence platform for senior executives. Use these tools, as the signed-in Aura user, to list active strategic signals, inspect a signal's evidence, review the user's recent LinkedIn posts, and capture new notes/articles into Aura for signal detection.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_signals_default, get_signal_default, list_posts_default, create_capture_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
